// Torque Input Map File
if (isObject(moveMap)) moveMap.delete();
new ActionMap(moveMap);
moveMap.bindCmd(keyboard, "escape", "", "handleEscape();");
moveMap.bind(keyboard, "a", moveleft);
moveMap.bind(keyboard, "d", moveright);
moveMap.bind(keyboard, "left", moveleft);
moveMap.bind(keyboard, "right", moveright);
moveMap.bind(keyboard, "w", moveForward);
moveMap.bind(keyboard, "s", movebackward);
moveMap.bind(keyboard, "up", moveForward);
moveMap.bind(keyboard, "down", movebackward);
moveMap.bind(keyboard, "e", moveup);
moveMap.bind(keyboard, "c", movedown);
moveMap.bind(keyboard, "space", jump);
moveMap.bind(keyboard, "f", setZoomFOV);
moveMap.bind(keyboard, "r", toggleZoom);
moveMap.bind(keyboard, "z", toggleFreeLook);
moveMap.bind(keyboard, "tab", toggleFirstPerson);
moveMap.bind(keyboard, "alt c", toggleCamera);
moveMap.bind(keyboard, "f3", startRecordingDemo);
moveMap.bind(keyboard, "f4", stopRecordingDemo);
moveMap.bind(keyboard, "f8", dropCameraAtPlayer);
moveMap.bind(keyboard, "f7", dropPlayerAtCamera);
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(mouse0, "button1", altTrigger);
moveMap.bind(gamepad0, "thumbrx", D, "-0.23 0.23", gamepadYaw);
moveMap.bind(gamepad0, "thumbry", D, "-0.23 0.23", gamepadPitch);
moveMap.bind(gamepad0, "thumblx", D, "-0.23 0.23", gamePadMoveX);
moveMap.bind(gamepad0, "thumbly", D, "-0.23 0.23", gamePadMoveY);
moveMap.bind(gamepad0, "btn_a", jump);
moveMap.bind(gamepad0, "btn_back", toggleCamera);
moveMap.bindCmd(gamepad0, "lpov", "toggleLightColorViz();", "");
moveMap.bindCmd(gamepad0, "upov", "toggleDepthViz();", "");
moveMap.bindCmd(gamepad0, "dpov", "toggleNormalsViz();", "");
moveMap.bindCmd(gamepad0, "rpov", "toggleLightSpecularViz();", "");
moveMap.bind(gamepad0, "triggerr", gamepadFire);
moveMap.bind(gamepad0, "triggerl", gamepadAltTrigger);
moveMap.bind(gamepad0, "btn_b", toggleZoom);
